version: '3.7'
services:
  trace:
    build:
        context: .
    restart: unless-stopped
    ports:
      - "${TRACE_PORT}:9999"
      - "${WS_PORT}:9998"
    command:
      - "0.0.0.0"
      - "9999"
      - "0.0.0.0"
      - "9998"
